nav:
  - Início: pt/index.md
  - LSDB: 
      - 2MASS: pt/lsdb/two_mass.md
      - DES: 
        - DES DR2: pt/lsdb/des_dr2.md
        - DES Y6 Gold: pt/lsdb/des_y6_gold.md
      - DELVE: pt/lsdb/delve.md
      - Gaia: pt/lsdb/gaia.md
  - Banco de Dados: 
      - 2MASS PSC: pt/database/two_mass_psc.md
      - DES:
        - DES DR2: pt/database/des_dr2.md
        - DES Y6 Gold: pt/database/des_y6_gold.md 
      - Gaia DR3: pt/database/gaia_dr3.md
      - LSST:
        - LSST DP0.2: pt/database/lsst_dp0_2.md 
        - LSST DP1: pt/database/lsst_dp1.md  
  - HPC: 
      - DES:
        - DES DR2: pt/hpc/des_dr2.md
        - DES Y6 Gold: pt/hpc/des_y6_gold.md 
      - LSST:
        - LSST DP0.2: pt/hpc/lsst_dp0.2.md 
        - LSST DP1: pt/hpc/lsst_dp1.md
# Site information
#docs_dir: docs
site_name:  Datasets 
site_author: LIneA team 
site_url: "https://datasets.linea.org.br"
repo_name: linea-it/datasets
repo_url: https://github.com/linea-it/datasets
edit_uri: 'edit/main/docs'
use_directory_urls: false
copyright: 'Copyright &copy; 2006 - 2025 LIneA'


# Configuration
theme:
  name: material
  custom_dir: linea-theme
  #logo: 'images/linea.png'
  logo: 'images/linea-logo.png'
  favicon: 'images/linea_favicon.png'
  font:
    text: Roboto, Arial
  features:
    - navigation.indexes


  palette:
      # Palette toggle for light mode
  - scheme: default
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
    #primary: '#283663'
    primary: '#ffdd00'
    accent: 'deep orange'

  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
    primary: 'grey'
    accent: 'deep orange'

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: material/home-circle
      link: https://www.linea.org.br
    - icon: fontawesome/brands/github
      link: https://github.com/linea-it
    - icon: material/twitter
      link: https://twitter.com/linea_org
    - icon: material/instagram
      link: https://instagram.com/linea_org
    - icon: material/facebook
      link: https://facebook.com/linea.org
    - icon: material/youtube
      link: https://youtube.com/@linea_org

# Extensions
markdown_extensions:
  - attr_list
  - meta
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: false
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets

plugins:
    - i18n:
        docs_structure: folder
        languages:
          - locale: pt
            name: Português
            build: true
            default: true
            site_name: "Datasets"                
          - locale: en
            name: English
            build: true
            site_name: "Datasets"    
            nav:
            - Home: en/index.md
            - LSDB: 
                - 2MASS: en/lsdb/two_mass.md
                - DES: 
                  - DES DR2: en/lsdb/des_dr2.md
                  - DES Y6 Gold: en/lsdb/des_y6_gold.md
                - DELVE: en/lsdb/delve.md
                - Gaia: en/lsdb/gaia.md
            - Banco de Dados: 
                - 2MASS PSC: en/database/two_mass_psc.md
                - DES:
                  - DES DR2: en/database/des_dr2.md
                  - DES Y6 Gold: en/database/des_y6_gold.md 
                - Gaia DR3: en/database/gaia_dr3.md
                - LSST:
                  - LSST DP0.2: en/database/lsst_dp0_2.md 
                  - LSST DP1: en/database/lsst_dp1.md  
            - HPC: 
                - DES:
                  - DES DR2: en/hpc/des_dr2.md
                  - DES Y6 Gold: en/hpc/des_y6_gold.md 
                - LSST:
                  - LSST DP0.2: en/hpc/lsst_dp0.2.md 
                  - LSST DP1: en/hpc/lsst_dp1.md
          - locale: es
            name: Español
            build: true
            nav:
            - Inicio: es/index.md
            - LSDB: 
                - 2MASS: es/lsdb/two_mass.md
                - DES: 
                  - DES DR2: es/lsdb/des_dr2.md
                  - DES Y6 Gold: es/lsdb/des_y6_gold.md
                - DELVE: es/lsdb/delve.md
                - Gaia: es/lsdb/gaia.md
            - Banco de Dados: 
                - 2MASS PSC: es/database/two_mass_psc.md
                - DES:
                  - DES DR2: es/database/des_dr2.md
                  - DES Y6 Gold: es/database/des_y6_gold.md 
                - Gaia DR3: es/database/gaia_dr3.md
                - LSST:
                  - LSST DP0.2: es/database/lsst_dp0_2.md 
                  - LSST DP1: es/database/lsst_dp1.md  
            - HPC: 
                - DES:
                  - DES DR2: es/hpc/des_dr2.md
                  - DES Y6 Gold: es/hpc/des_y6_gold.md 
                - LSST:
                  - LSST DP0.2: es/hpc/lsst_dp0.2.md 
                  - LSST DP1: es/hpc/lsst_dp1.md   
    - search:
        enabled: true
    - git-revision-date-localized:
        type: date
    #- mkdocs-video
