nav:
  - Home: en/index.md
  - HATS: 
      - DES: en/hats/des.md
      - DELVE: en/hats/delve.md
  - User Query: 
      - DES: en/user_query/des.md
      - Gaia: en/gaia/des.md
      - 2MASS: en/two_mass/des.md
  

  #- SDSS: en/sdss.md
  #- 2MASS: en/2mass.md
  #- DESI: en/desi.md
  #- Gaia: en/gaia.md
  #- WISE: en/wise.md 


# Site information
#docs_dir: docs
site_name:  Datasets 
site_author: LIneA team 
site_url: "https://datasets.linea.org.br"
repo_name: linea-it/datasets
repo_url: https://github.com/linea-it/datasets
edit_uri: 'edit/main/docs'
use_directory_urls: false
copyright: 'Copyright &copy; 2006 - 2025 LIneA'


# Configuration
theme:
  name: material
  custom_dir: linea-theme
  #logo: 'images/linea.png'
  logo: 'images/linea-logo.png'
  favicon: 'images/linea_favicon.png'
  font:
    text: Roboto, Arial
  features:
    - navigation.indexes


  palette:
      # Palette toggle for light mode
  - scheme: default
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
    #primary: '#283663'
    primary: '#ffdd00'
    accent: 'deep orange'

  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
    primary: 'grey'
    accent: 'deep orange'

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: material/home-circle
      link: https://www.linea.org.br
    - icon: fontawesome/brands/github
      link: https://github.com/linea-it
    - icon: material/twitter
      link: https://twitter.com/linea_org
    - icon: material/instagram
      link: https://instagram.com/linea_org
    - icon: material/facebook
      link: https://facebook.com/linea.org
    - icon: material/youtube
      link: https://youtube.com/@linea_org

# Extensions
markdown_extensions:
  - attr_list
  - meta
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: false
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.snippets

plugins:
    - i18n:
        docs_structure: folder
        languages:
          - locale: en
            default: true
            name: English
            build: true
            site_name: "Datasets"    
          - locale: pt
            name: Português
            build: true
            nav:
              - Home: pt/index.md
              - HATS: 
                  - DES: pt/hats/des.md
                  - DELVE: pt/hats/delve.md
              - User Query: 
                  - DES: pt/user_query/des.md
                  - Gaia: pt/gaia/des.md
                  - 2MASS: pt/two_mass/des.md     
          - locale: es
            name: Español
            build: true
            nav:
              - Home: es/index.md
              - HATS: 
                  - DES: es/hats/des.md
                  - DELVE: es/hats/delve.md
              - User Query: 
                  - DES: es/user_query/des.md
                  - Gaia: es/gaia/des.md
                  - 2MASS: es/two_mass/des.md     
    - search:
        enabled: true
    - git-revision-date-localized:
        type: date
    #- mkdocs-video
